In [1]:
import numpy as np

Arithmetic operation

In [13]:
a1=np.arange(1,6)
a2=np.arange(6,11)

In [14]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [15]:
a1-a2

array([-5, -5, -5, -5, -5])

In [16]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [17]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [18]:
a1//a2

array([0, 0, 0, 0, 0])

In [19]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [97]:
a1=np.arange(1,11).reshape(2,5)
a2=np.arange(11,21).reshape(2,5)
a3=np.arange(11,21).reshape(5,2)

In [95]:
a1+a2

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [96]:
a1*a2

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [42]:
a1**a2

array([[                  1,                4096,             1594323,
                  268435456,         30517578125],
       [      2821109907456,     232630513987207,   18014398509481984,
        1350851717672992089, 7766279631452241920]])

In [43]:
a1/a2

array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
       [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]])

BROADCASTING


In [30]:
l=list(range(10,60,10))
l

[10, 20, 30, 40, 50]

In [37]:
l+10

TypeError: can only concatenate list (not "int") to list

In [33]:
arr=np.array(l)
arr

array([10, 20, 30, 40, 50])

In [34]:
arr+10

array([20, 30, 40, 50, 60])

DEEP VS SHALLOW COPY


In [63]:
a=np.arange(20,50,2)
a

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [64]:
slice=a[:5]
slice

array([20, 22, 24, 26, 28])

In [67]:
slice += 10
slice

array([40, 42, 44, 46, 48])

In [69]:
a

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [77]:
b=a

In [78]:
b[0]=23
b

array([23, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [79]:
a

array([23, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [80]:
b=a.copy()

In [82]:
b[0]=24
b

array([24, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [83]:
a

array([23, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

MATRIX OPERATION

In [84]:
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [85]:
a2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [86]:
a1+a2

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [88]:
a1*a2

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [99]:
a1 @ a3

array([[245, 260],
       [620, 660]])

In [100]:
np.dot(a1,a3)

array([[245, 260],
       [620, 660]])

In [101]:
a1.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [102]:
np.transpose(a1)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [108]:
matrixA=np.random.randint(10,50,25).reshape(5,5)
matrixA

array([[19, 28, 27, 40, 26],
       [21, 25, 30, 22, 18],
       [35, 19, 42, 44, 13],
       [23, 28, 43, 25, 20],
       [35, 29, 41, 33, 48]], dtype=int32)

In [112]:
det_matrixA=np.linalg.det(matrixA)
det_matrixA

np.float64(3051278.999999999)

In [113]:
inv_matrixA=np.linalg.inv(matrixA)
inv_matrixA

array([[-0.05585658,  0.14650283,  0.02954237, -0.10756375,  0.01213426],
       [ 0.00690006,  0.13993411, -0.02756483, -0.04738111, -0.02900521],
       [-0.00452433, -0.10999289,  0.00078524,  0.10055554,  0.0015872 ],
       [ 0.04244941, -0.05419563,  0.0150881 ,  0.00474785, -0.0087347 ],
       [ 0.01124053, -0.06015674, -0.01593135,  0.01790266,  0.03415879]])

ADVANCE ARRAY MANUPULATION

ARRAY STACK

In [ ]:
a=np.arange(1,6)
b=np.arange(6,11)

In [119]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [120]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Array SPLITTING

In [123]:
c=np.random.randint(100,200,16).reshape(4,4)
c

array([[158, 161, 165, 137],
       [198, 191, 102, 137],
       [121, 178, 132, 191],
       [106, 160, 163, 147]], dtype=int32)

In [125]:
np.hsplit(c,2)

[array([[158, 161],
        [198, 191],
        [121, 178],
        [106, 160]], dtype=int32),
 array([[165, 137],
        [102, 137],
        [132, 191],
        [163, 147]], dtype=int32)]

In [127]:
np.vsplit(c,4)

[array([[158, 161, 165, 137]], dtype=int32),
 array([[198, 191, 102, 137]], dtype=int32),
 array([[121, 178, 132, 191]], dtype=int32),
 array([[106, 160, 163, 147]], dtype=int32)]

In [128]:
np.hsplit(c,3)

ValueError: array split does not result in an equal division