In [2]:
import numpy as np

INDEXING AND SLICING OF VECTOR 


In [7]:
arr=np.arange(11,100,4)
arr

array([11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75,
       79, 83, 87, 91, 95, 99])

In [8]:
arr[9]

np.int64(47)

In [9]:
arr[2:5]

array([19, 23, 27])

In [10]:
arr[2::4]

array([19, 35, 51, 67, 83, 99])

MATRIX INDEXING AND SLICING

In [26]:
arr=np.random.randint(100,200,30).reshape(6,5)
arr

array([[146, 180, 191, 180, 178],
       [105, 131, 159, 170, 189],
       [123, 194, 161, 171, 111],
       [179, 107, 117, 129, 146],
       [179, 180, 167, 137, 196],
       [164, 119, 162, 196, 179]], dtype=int32)

In [21]:
arr[0]

array([3507672, 2874996, 5924574, 9414576, 7262844], dtype=int32)

In [22]:
arr[0][1]

np.int32(2874996)

In [23]:
arr[0,1]

np.int32(2874996)

In [27]:
arr[3:,3:]

array([[129, 146],
       [137, 196],
       [196, 179]], dtype=int32)

In [28]:
arr[0]

array([146, 180, 191, 180, 178], dtype=int32)

In [30]:
arr[0:2]

array([[146, 180, 191, 180, 178],
       [105, 131, 159, 170, 189]], dtype=int32)

In [32]:
arr[:,2]

array([191, 159, 161, 117, 167, 162], dtype=int32)

In [34]:
bool_index=arr%2==0
bool_index

array([[ True,  True, False,  True,  True],
       [False, False, False,  True, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True],
       [False,  True, False, False,  True],
       [ True, False,  True,  True, False]])