In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
arr=np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [12]:
arr=np.zeros((6,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
arr=np.arange(2,101,2)
arr

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [21]:
arr=np.linspace(2,10,100)
arr

array([ 2.        ,  2.08080808,  2.16161616,  2.24242424,  2.32323232,
        2.4040404 ,  2.48484848,  2.56565657,  2.64646465,  2.72727273,
        2.80808081,  2.88888889,  2.96969697,  3.05050505,  3.13131313,
        3.21212121,  3.29292929,  3.37373737,  3.45454545,  3.53535354,
        3.61616162,  3.6969697 ,  3.77777778,  3.85858586,  3.93939394,
        4.02020202,  4.1010101 ,  4.18181818,  4.26262626,  4.34343434,
        4.42424242,  4.50505051,  4.58585859,  4.66666667,  4.74747475,
        4.82828283,  4.90909091,  4.98989899,  5.07070707,  5.15151515,
        5.23232323,  5.31313131,  5.39393939,  5.47474747,  5.55555556,
        5.63636364,  5.71717172,  5.7979798 ,  5.87878788,  5.95959596,
        6.04040404,  6.12121212,  6.2020202 ,  6.28282828,  6.36363636,
        6.44444444,  6.52525253,  6.60606061,  6.68686869,  6.76767677,
        6.84848485,  6.92929293,  7.01010101,  7.09090909,  7.17171717,
        7.25252525,  7.33333333,  7.41414141,  7.49494949,  7.57

In [4]:
arr=np.random.rand(5,10)
arr


array([[0.16914834, 0.15514063, 0.28798085, 0.98050916, 0.18344032,
        0.35991601, 0.84080102, 0.54016152, 0.73844912, 0.68727513],
       [0.26592866, 0.12527957, 0.49894533, 0.81115322, 0.49515604,
        0.7119657 , 0.94315889, 0.72652826, 0.39863224, 0.05645518],
       [0.07706412, 0.2714047 , 0.71540979, 0.37456761, 0.88093577,
        0.54223517, 0.84967169, 0.79447709, 0.95330282, 0.72947589],
       [0.4488378 , 0.08444401, 0.27586512, 0.97730816, 0.06220378,
        0.21185335, 0.01608183, 0.76721124, 0.39093088, 0.57972236],
       [0.48324316, 0.99294818, 0.61974936, 0.66888247, 0.2552765 ,
        0.13427036, 0.89496037, 0.53671321, 0.14540485, 0.88234155]])

In [19]:
np.random.randn(4)

array([1.60884345, 0.48445613, 0.71898022, 1.27908722])

In [27]:
np.random.randint(6,1000,40)

array([748, 861, 137, 388, 319, 854, 972, 711, 129, 790,  96, 612, 292,
       687, 225, 894, 456, 535, 281, 797, 779, 125, 499, 902, 416, 991,
        63, 507, 735, 642, 355, 349, 995, 991, 868,  85, 403, 998, 342,
       333], dtype=int32)

Auto Matrix Creation


In [42]:
arr=np.arange(1, 13).reshape(3, 4)

In [45]:
np.random.randint(2,100,40).reshape(10,4)

array([[99, 42,  6, 80],
       [ 2, 22, 43, 49],
       [39, 97, 61, 95],
       [50, 71, 36, 45],
       [ 4, 83,  3, 62],
       [11, 96, 79,  7],
       [60, 87, 70, 13],
       [74,  9, 26,  6],
       [88, 26, 85,  3],
       [54, 25, 92, 39]], dtype=int32)

In [46]:
np.random.rand(3,4)

array([[0.14631082, 0.19890182, 0.56049131, 0.19317365],
       [0.15012654, 0.4024027 , 0.13042864, 0.64294831],
       [0.31974017, 0.73989941, 0.12185665, 0.36452218]])

In [7]:
np.random.randn(10,10)

array([[-0.17255637,  1.45614331, -0.43946354,  1.44359047,  0.23792802,
         0.42580924, -0.37193127,  0.01391756, -1.37945408, -1.52813389],
       [-0.07040466, -0.34116369, -0.91750452,  1.6618908 , -0.16623908,
        -0.17460773,  0.17869808,  0.13496173,  2.61055711,  0.88365235],
       [-2.03583268, -0.70132353, -0.31801424,  0.87121102, -0.1781533 ,
        -0.4656244 ,  1.29269919, -1.42262309, -0.05238282, -1.35364177],
       [-0.86938226,  0.29519726, -0.11544923,  0.49239585,  0.29809857,
        -0.87340488,  0.77810989, -1.22839347, -0.79885478,  0.41848277],
       [ 0.80974211,  2.66227065,  0.14742996,  0.63723521,  0.8973891 ,
         1.71102955, -0.41466623,  2.82745831,  1.05808533, -0.03490849],
       [-0.68417467,  0.44509807,  1.04776715,  0.08056792,  0.15761193,
         0.10536088, -0.18396169, -1.33790302, -0.46580173, -2.06825407],
       [ 0.69767153, -0.42236481,  0.83042496,  0.67918695, -0.03088536,
        -1.00186023, -0.10186031, -1.5928411 

In [16]:
np.linspace(-2,2,100).reshape(10,10)


array([[-2.        , -1.95959596, -1.91919192, -1.87878788, -1.83838384,
        -1.7979798 , -1.75757576, -1.71717172, -1.67676768, -1.63636364],
       [-1.5959596 , -1.55555556, -1.51515152, -1.47474747, -1.43434343,
        -1.39393939, -1.35353535, -1.31313131, -1.27272727, -1.23232323],
       [-1.19191919, -1.15151515, -1.11111111, -1.07070707, -1.03030303,
        -0.98989899, -0.94949495, -0.90909091, -0.86868687, -0.82828283],
       [-0.78787879, -0.74747475, -0.70707071, -0.66666667, -0.62626263,
        -0.58585859, -0.54545455, -0.50505051, -0.46464646, -0.42424242],
       [-0.38383838, -0.34343434, -0.3030303 , -0.26262626, -0.22222222,
        -0.18181818, -0.14141414, -0.1010101 , -0.06060606, -0.02020202],
       [ 0.02020202,  0.06060606,  0.1010101 ,  0.14141414,  0.18181818,
         0.22222222,  0.26262626,  0.3030303 ,  0.34343434,  0.38383838],
       [ 0.42424242,  0.46464646,  0.50505051,  0.54545455,  0.58585859,
         0.62626263,  0.66666667,  0.70707071

In [17]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [26]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

METHODS AND PROPERTIES

In [24]:
arr.shape

(8,)

In [27]:
arr.size

6

In [28]:
arr.dtype

dtype('float64')

In [30]:
arr.device

'cpu'

In [8]:
arr=np.random.randint(1,15,9).reshape(3,3)
arr

array([[ 4,  1,  7],
       [ 2,  8,  2],
       [12,  4, 11]], dtype=int32)

In [39]:
arr.max()

np.int32(5)

In [40]:
arr.min()

np.int32(2)

In [41]:
arr.sum()

np.int64(24)

columnwise SUM

In [9]:
np.sum(arr,axis=0)

array([18, 13, 20])

ROWWISE SUM

In [10]:
np.sum(arr,axis=1)

array([12, 12, 27])

In [46]:
arr.mean()

np.float64(4.0)

In [47]:
arr.std()

np.float64(1.1547005383792515)

In [48]:
arr.argmax()

np.int64(0)

In [49]:
arr.argmin()

np.int64(1)